### ISSUE TITLE
Not working on Windows 10

### ISSUE THREAD

**Issue by clabnet** [G-Fidalgo/cypress-runner#7]
- Open VSCode on Windows 10
- Install extension

The command path to execute cypress contain the slash and not the backslash
```
D:\_PROJECTS\POMINI\labs\vue-e2e>"d:/_PROJECTS/POMINI/labs/vue-e2e/node_modules/cypress/bin/cypress" run --spec "d:\_PROJECTS\POMINI\labs\vue-e2e\cypress\e2e\pomini-api\nuovo.cy.js"
```

**Comment by G-Fidalgo** [comment]
Hi @clabnet thank you for the openned issue, already released v 2.0.0 that solves the issue that you had and should properly work on Windows OS 

Also enhanced Cypress V 10 and higher :)
